# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognizer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10recognizer.proto\x12\nrecognizer\"\x17\n\x08ImageURL\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x16\n\x07\x41\x63\x63ount\x12\x0b\n\x03msg\x18\x01 \x01(\t2E\n\x0cImageService\x12\x35\n\x08ImageReq\x12\x14.recognizer.ImageURL\x1a\x13.recognizer.AccountB\nZ\x08pkg/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognizer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010pkg/grpc'
  _globals['_IMAGEURL']._serialized_start=32
  _globals['_IMAGEURL']._serialized_end=55
  _globals['_ACCOUNT']._serialized_start=57
  _globals['_ACCOUNT']._serialized_end=79
  _globals['_IMAGESERVICE']._serialized_start=81
  _globals['_IMAGESERVICE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
